#pragma once

#include_next <mcuconf.h>

/* Setup USART for split communication */
#undef STM32_SERIAL_USE_USART2
#define STM32_SERIAL_USE_USART2 TRUE

/* MCU clock settings */
#undef STM32_HSE_BYPASS
#undef STM32_HSE_ENABLED
#undef STM32_SW
#undef STM32_PLLSRC
#undef STM32_PLLM_VALUE
#undef STM32_PLLN_VALUE
#undef STM32_PLLP_VALUE
#undef STM32_PLLQ_VALUE
#undef STM32_PLLR_VALUE
#undef STM32_HPRE
#undef STM32_PPRE
#undef STM32_USBSEL
#undef STM32_USART2SEL

#define STM32_HSE_ENABLED TRUE
#define STM32_SW STM32_SW_PLLRCLK
#define STM32_PLLSRC STM32_PLLSRC_HSE
#define STM32_PLLM_VALUE 1U
#define STM32_PLLN_VALUE 24U
#define STM32_PLLP_VALUE 2U
#define STM32_PLLQ_VALUE 4U
#define STM32_PLLR_VALUE 3U
#define STM32_HPRE STM32_HPRE_DIV1
#define STM32_PPRE STM32_PPRE_DIV1
#define STM32_USBSEL STM32_USBSEL_PLLQCLK
#define STM32_USART2SEL STM32_USART2SEL_SYSCLK

/* Setup OLED display communication */
#undef STM32_SPI_USE_SPI1
#define STM32_SPI_USE_SPI1 TRUE
#define SPI_SELECT_MODE SPI_SELECT_MODE_NONE
